//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profissionais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profissionais()
        {
            this.Agendas = new HashSet<Agendas>();
            this.Clientes = new HashSet<Clientes>();
            this.Documentos = new HashSet<Documentos>();
            this.Processos = new HashSet<Processos>();
            this.ProcessosAgendaProfissional = new HashSet<ProcessosAgendaProfissional>();
            this.TemplatesIniciaisAposentadoria = new HashSet<TemplatesIniciaisAposentadoria>();
            this.AgendasMassa = new HashSet<AgendasMassa>();
            this.PreAgendamento = new HashSet<PreAgendamento>();
        }
    
        public int ID { get; set; }
        public int IDPessoa { get; set; }
        public int IDTipoProfissional { get; set; }
        public Nullable<decimal> PercentualParticipacao { get; set; }
        public string OAB { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendas> Agendas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentos> Documentos { get; set; }
        public virtual Pessoas Pessoas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Processos> Processos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessosAgendaProfissional> ProcessosAgendaProfissional { get; set; }
        public virtual ProfissionaisTipos ProfissionaisTipos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplatesIniciaisAposentadoria> TemplatesIniciaisAposentadoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgendasMassa> AgendasMassa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreAgendamento> PreAgendamento { get; set; }
    }
}
