//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Data
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Uranus.Domain;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System;
    
    public partial class UranusEntities : DbContext
    {
        public UranusEntities()
            : base("name=UranusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agendas> Agendas { get; set; }
        public virtual DbSet<AgendasMassaHistorico> AgendasMassaHistorico { get; set; }
        public virtual DbSet<AgendasTipos> AgendasTipos { get; set; }
        public virtual DbSet<Alertas> Alertas { get; set; }
        public virtual DbSet<Auditoria> Auditoria { get; set; }
        public virtual DbSet<Bancos> Bancos { get; set; }
        public virtual DbSet<BancosLancamentos> BancosLancamentos { get; set; }
        public virtual DbSet<Caixas> Caixas { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<ClientesContratos> ClientesContratos { get; set; }
        public virtual DbSet<Cumpridos> Cumpridos { get; set; }
        public virtual DbSet<Documentos> Documentos { get; set; }
        public virtual DbSet<Email> Email { get; set; }
        public virtual DbSet<Feriados> Feriados { get; set; }
        public virtual DbSet<Fones> Fones { get; set; }
        public virtual DbSet<Fornecedores> Fornecedores { get; set; }
        public virtual DbSet<FornecedoresContratos> FornecedoresContratos { get; set; }
        public virtual DbSet<FornecedoresEmail> FornecedoresEmail { get; set; }
        public virtual DbSet<FornecedoresFones> FornecedoresFones { get; set; }
        public virtual DbSet<FornecedoresNotas> FornecedoresNotas { get; set; }
        public virtual DbSet<FornecedoresNotasParcelas> FornecedoresNotasParcelas { get; set; }
        public virtual DbSet<Historicos> Historicos { get; set; }
        public virtual DbSet<Modelos> Modelos { get; set; }
        public virtual DbSet<NotasServicos> NotasServicos { get; set; }
        public virtual DbSet<NotasServicosParcelas> NotasServicosParcelas { get; set; }
        public virtual DbSet<Parceiros> Parceiros { get; set; }
        public virtual DbSet<Pessoas> Pessoas { get; set; }
        public virtual DbSet<Processos> Processos { get; set; }
        public virtual DbSet<ProcessosAcoes> ProcessosAcoes { get; set; }
        public virtual DbSet<ProcessosAcoesEventos> ProcessosAcoesEventos { get; set; }
        public virtual DbSet<ProcessosAgendaProfissional> ProcessosAgendaProfissional { get; set; }
        public virtual DbSet<ProcessosAreas> ProcessosAreas { get; set; }
        public virtual DbSet<ProcessosAutores> ProcessosAutores { get; set; }
        public virtual DbSet<ProcessosCadastroAcao> ProcessosCadastroAcao { get; set; }
        public virtual DbSet<ProcessosEventos> ProcessosEventos { get; set; }
        public virtual DbSet<ProcessosEventosPendentes> ProcessosEventosPendentes { get; set; }
        public virtual DbSet<ProcessosIndicacoesTipos> ProcessosIndicacoesTipos { get; set; }
        public virtual DbSet<ProcessosPartes> ProcessosPartes { get; set; }
        public virtual DbSet<ProcessosPartesAdvogados> ProcessosPartesAdvogados { get; set; }
        public virtual DbSet<ProcessosVara> ProcessosVara { get; set; }
        public virtual DbSet<Profissionais> Profissionais { get; set; }
        public virtual DbSet<ProfissionaisTipos> ProfissionaisTipos { get; set; }
        public virtual DbSet<Salas> Salas { get; set; }
        public virtual DbSet<Sedes> Sedes { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<TemplatesIniciaisAposentadoria> TemplatesIniciaisAposentadoria { get; set; }
        public virtual DbSet<TemplatesIniciaisAposentadoriaPeriodos> TemplatesIniciaisAposentadoriaPeriodos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<UsuariosConectados> UsuariosConectados { get; set; }
        public virtual DbSet<Eventos> Eventos { get; set; }
        public virtual DbSet<cad_pessoa_limpa> cad_pessoa_limpa { get; set; }
        public virtual DbSet<View_EventosAutomaticos> View_EventosAutomaticos { get; set; }
        public virtual DbSet<View_Processos_Listagem> View_Processos_Listagem { get; set; }
        public virtual DbSet<View_ProcessosAgendasProfissionais_Listagem> View_ProcessosAgendasProfissionais_Listagem { get; set; }
        public virtual DbSet<AgendasMassa> AgendasMassa { get; set; }
        public virtual DbSet<PreAgendamento> PreAgendamento { get; set; }
        public virtual DbSet<PreCadastro> PreCadastro { get; set; }
        public virtual DbSet<AppConfiguracao> AppConfiguracao { get; set; }
        public virtual DbSet<Profissoes> Profissoes { get; set; }
        public virtual DbSet<PessoasUsuariosAplicativo> PessoasUsuariosAplicativo { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
    
        [DbFunction("UranusEntities", "fnBuscarClientes")]
        public virtual IQueryable<fnBuscarClientes_Result> fnBuscarClientes(string nome)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnBuscarClientes_Result>("[UranusEntities].[fnBuscarClientes](@Nome)", nomeParameter);
        }
    
        [DbFunction("UranusEntities", "fnBuscarClientesFiltros")]
        public virtual IQueryable<fnBuscarClientesFiltros_Result> fnBuscarClientesFiltros(string nome, string cpf, string fone, string email, string dataNascimento)
        {
            var nomeParameter = nome != null ?
                new ObjectParameter("Nome", nome) :
                new ObjectParameter("Nome", typeof(string));
    
            var cpfParameter = cpf != null ?
                new ObjectParameter("Cpf", cpf) :
                new ObjectParameter("Cpf", typeof(string));
    
            var foneParameter = fone != null ?
                new ObjectParameter("Fone", fone) :
                new ObjectParameter("Fone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var dataNascimentoParameter = dataNascimento != null ?
                new ObjectParameter("DataNascimento", dataNascimento) :
                new ObjectParameter("DataNascimento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnBuscarClientesFiltros_Result>("[UranusEntities].[fnBuscarClientesFiltros](@Nome, @Cpf, @Fone, @Email, @DataNascimento)", nomeParameter, cpfParameter, foneParameter, emailParameter, dataNascimentoParameter);
        }
    
        [DbFunction("UranusEntities", "fnRelatorioPorSede")]
        public virtual IQueryable<fnRelatorioPorSede_Result> fnRelatorioPorSede(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal, string cliente, string sedes, string acoes, string areas, string juizos)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("dataInicial", dataInicial) :
                new ObjectParameter("dataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("dataFinal", dataFinal) :
                new ObjectParameter("dataFinal", typeof(System.DateTime));
    
            var clienteParameter = cliente != null ?
                new ObjectParameter("Cliente", cliente) :
                new ObjectParameter("Cliente", typeof(string));
    
            var sedesParameter = sedes != null ?
                new ObjectParameter("Sedes", sedes) :
                new ObjectParameter("Sedes", typeof(string));
    
            var acoesParameter = acoes != null ?
                new ObjectParameter("Acoes", acoes) :
                new ObjectParameter("Acoes", typeof(string));
    
            var areasParameter = areas != null ?
                new ObjectParameter("Areas", areas) :
                new ObjectParameter("Areas", typeof(string));
    
            var juizosParameter = juizos != null ?
                new ObjectParameter("Juizos", juizos) :
                new ObjectParameter("Juizos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnRelatorioPorSede_Result>("[UranusEntities].[fnRelatorioPorSede](@dataInicial, @dataFinal, @Cliente, @Sedes, @Acoes, @Areas, @Juizos)", dataInicialParameter, dataFinalParameter, clienteParameter, sedesParameter, acoesParameter, areasParameter, juizosParameter);
        }
    
        [DbFunction("UranusEntities", "PesquisarProcessosAgendasProfissionais")]
        public virtual IQueryable<PesquisarProcessosAgendasProfissionais_Result> PesquisarProcessosAgendasProfissionais(string nomeAutor, string nomeParte)
        {
            var nomeAutorParameter = nomeAutor != null ?
                new ObjectParameter("NomeAutor", nomeAutor) :
                new ObjectParameter("NomeAutor", typeof(string));
    
            var nomeParteParameter = nomeParte != null ?
                new ObjectParameter("NomeParte", nomeParte) :
                new ObjectParameter("NomeParte", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<PesquisarProcessosAgendasProfissionais_Result>("[UranusEntities].[PesquisarProcessosAgendasProfissionais](@NomeAutor, @NomeParte)", nomeAutorParameter, nomeParteParameter);
        }
    
        public virtual int ProcessosAnteriores2009()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcessosAnteriores2009");
        }
    
        [DbFunction("UranusEntities", "RelatorioAgendaCompromisso")]
        public virtual IQueryable<RelatorioAgendaCompromisso_Result> RelatorioAgendaCompromisso(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("dataInicial", dataInicial) :
                new ObjectParameter("dataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("dataFinal", dataFinal) :
                new ObjectParameter("dataFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<RelatorioAgendaCompromisso_Result>("[UranusEntities].[RelatorioAgendaCompromisso](@dataInicial, @dataFinal)", dataInicialParameter, dataFinalParameter);
        }
    
        [DbFunction("UranusEntities", "RelatorioAgendaProfissionais")]
        public virtual IQueryable<RelatorioAgendaProfissionais_Result> RelatorioAgendaProfissionais(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal, Nullable<System.DateTime> dataCumprimentoPrazoInicial, Nullable<System.DateTime> dataCumprimentoPrazoFinal)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("dataInicial", dataInicial) :
                new ObjectParameter("dataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("dataFinal", dataFinal) :
                new ObjectParameter("dataFinal", typeof(System.DateTime));
    
            var dataCumprimentoPrazoInicialParameter = dataCumprimentoPrazoInicial.HasValue ?
                new ObjectParameter("DataCumprimentoPrazoInicial", dataCumprimentoPrazoInicial) :
                new ObjectParameter("DataCumprimentoPrazoInicial", typeof(System.DateTime));
    
            var dataCumprimentoPrazoFinalParameter = dataCumprimentoPrazoFinal.HasValue ?
                new ObjectParameter("DataCumprimentoPrazoFinal", dataCumprimentoPrazoFinal) :
                new ObjectParameter("DataCumprimentoPrazoFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<RelatorioAgendaProfissionais_Result>("[UranusEntities].[RelatorioAgendaProfissionais](@dataInicial, @dataFinal, @DataCumprimentoPrazoInicial, @DataCumprimentoPrazoFinal)", dataInicialParameter, dataFinalParameter, dataCumprimentoPrazoInicialParameter, dataCumprimentoPrazoFinalParameter);
        }
    
        [DbFunction("UranusEntities", "RelatorioAgendaProfissionaisPrazos")]
        public virtual IQueryable<RelatorioAgendaProfissionaisPrazos_Result> RelatorioAgendaProfissionaisPrazos(Nullable<System.DateTime> dataPrazo1Inicial, Nullable<System.DateTime> dataPrazo1Final, Nullable<System.DateTime> dataPrazo2Inicial, Nullable<System.DateTime> dataPrazo2Final)
        {
            var dataPrazo1InicialParameter = dataPrazo1Inicial.HasValue ?
                new ObjectParameter("dataPrazo1Inicial", dataPrazo1Inicial) :
                new ObjectParameter("dataPrazo1Inicial", typeof(System.DateTime));
    
            var dataPrazo1FinalParameter = dataPrazo1Final.HasValue ?
                new ObjectParameter("dataPrazo1Final", dataPrazo1Final) :
                new ObjectParameter("dataPrazo1Final", typeof(System.DateTime));
    
            var dataPrazo2InicialParameter = dataPrazo2Inicial.HasValue ?
                new ObjectParameter("dataPrazo2Inicial", dataPrazo2Inicial) :
                new ObjectParameter("dataPrazo2Inicial", typeof(System.DateTime));
    
            var dataPrazo2FinalParameter = dataPrazo2Final.HasValue ?
                new ObjectParameter("dataPrazo2Final", dataPrazo2Final) :
                new ObjectParameter("dataPrazo2Final", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<RelatorioAgendaProfissionaisPrazos_Result>("[UranusEntities].[RelatorioAgendaProfissionaisPrazos](@dataPrazo1Inicial, @dataPrazo1Final, @dataPrazo2Inicial, @dataPrazo2Final)", dataPrazo1InicialParameter, dataPrazo1FinalParameter, dataPrazo2InicialParameter, dataPrazo2FinalParameter);
        }
    
        [DbFunction("UranusEntities", "RelatorioAgendasNaoCompareceu")]
        public virtual IQueryable<RelatorioAgendasNaoCompareceu_Result> RelatorioAgendasNaoCompareceu(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("dataInicial", dataInicial) :
                new ObjectParameter("dataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("dataFinal", dataFinal) :
                new ObjectParameter("dataFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<RelatorioAgendasNaoCompareceu_Result>("[UranusEntities].[RelatorioAgendasNaoCompareceu](@dataInicial, @dataFinal)", dataInicialParameter, dataFinalParameter);
        }
    
        [DbFunction("UranusEntities", "RelatorioCancelamentoAgenda")]
        public virtual IQueryable<RelatorioCancelamentoAgenda_Result> RelatorioCancelamentoAgenda(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal, Nullable<System.DateTime> dataCancelamentoInicial, Nullable<System.DateTime> dataCancelamentoFinal)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("DataInicial", dataInicial) :
                new ObjectParameter("DataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("DataFinal", dataFinal) :
                new ObjectParameter("DataFinal", typeof(System.DateTime));
    
            var dataCancelamentoInicialParameter = dataCancelamentoInicial.HasValue ?
                new ObjectParameter("DataCancelamentoInicial", dataCancelamentoInicial) :
                new ObjectParameter("DataCancelamentoInicial", typeof(System.DateTime));
    
            var dataCancelamentoFinalParameter = dataCancelamentoFinal.HasValue ?
                new ObjectParameter("DataCancelamentoFinal", dataCancelamentoFinal) :
                new ObjectParameter("DataCancelamentoFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<RelatorioCancelamentoAgenda_Result>("[UranusEntities].[RelatorioCancelamentoAgenda](@DataInicial, @DataFinal, @DataCancelamentoInicial, @DataCancelamentoFinal)", dataInicialParameter, dataFinalParameter, dataCancelamentoInicialParameter, dataCancelamentoFinalParameter);
        }
    
        [DbFunction("UranusEntities", "RelatorioClientesEtiquetas")]
        public virtual IQueryable<RelatorioClientesEtiquetas_Result> RelatorioClientesEtiquetas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<RelatorioClientesEtiquetas_Result>("[UranusEntities].[RelatorioClientesEtiquetas]()");
        }
    
        [DbFunction("UranusEntities", "RelatorioClientesGeral")]
        public virtual IQueryable<RelatorioClientesGeral_Result> RelatorioClientesGeral(Nullable<int> idSede)
        {
            var idSedeParameter = idSede.HasValue ?
                new ObjectParameter("IdSede", idSede) :
                new ObjectParameter("IdSede", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<RelatorioClientesGeral_Result>("[UranusEntities].[RelatorioClientesGeral](@IdSede)", idSedeParameter);
        }
    
        [DbFunction("UranusEntities", "RelatorioClientesIndicacao")]
        public virtual IQueryable<RelatorioClientesIndicacao_Result> RelatorioClientesIndicacao()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<RelatorioClientesIndicacao_Result>("[UranusEntities].[RelatorioClientesIndicacao]()");
        }
    
        [DbFunction("UranusEntities", "RelatorioEventos")]
        public virtual IQueryable<RelatorioEventos_Result> RelatorioEventos(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("dataInicial", dataInicial) :
                new ObjectParameter("dataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("dataFinal", dataFinal) :
                new ObjectParameter("dataFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<RelatorioEventos_Result>("[UranusEntities].[RelatorioEventos](@dataInicial, @dataFinal)", dataInicialParameter, dataFinalParameter);
        }
    
        [DbFunction("UranusEntities", "RelatorioEventosPorClientes")]
        public virtual IQueryable<RelatorioEventosPorClientes_Result> RelatorioEventosPorClientes(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("dataInicial", dataInicial) :
                new ObjectParameter("dataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("dataFinal", dataFinal) :
                new ObjectParameter("dataFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<RelatorioEventosPorClientes_Result>("[UranusEntities].[RelatorioEventosPorClientes](@dataInicial, @dataFinal)", dataInicialParameter, dataFinalParameter);
        }
    
        public virtual int ReltorioIndicacao()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ReltorioIndicacao");
        }
    
        [DbFunction("UranusEntities", "SplitString")]
        public virtual IQueryable<string> SplitString(string input, string character)
        {
            var inputParameter = input != null ?
                new ObjectParameter("Input", input) :
                new ObjectParameter("Input", typeof(string));
    
            var characterParameter = character != null ?
                new ObjectParameter("Character", character) :
                new ObjectParameter("Character", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[UranusEntities].[SplitString](@Input, @Character)", inputParameter, characterParameter);
        }
    
        public virtual int stpAjustaProcessosTratamento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stpAjustaProcessosTratamento");
        }
    
        public virtual ObjectResult<stpAjustarProcessos_Result> stpAjustarProcessos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stpAjustarProcessos_Result>("stpAjustarProcessos");
        }
    
        public virtual int stpAlterarClienteAgenda(string nomeOrigem, string nomeDestino)
        {
            var nomeOrigemParameter = nomeOrigem != null ?
                new ObjectParameter("NomeOrigem", nomeOrigem) :
                new ObjectParameter("NomeOrigem", typeof(string));
    
            var nomeDestinoParameter = nomeDestino != null ?
                new ObjectParameter("NomeDestino", nomeDestino) :
                new ObjectParameter("NomeDestino", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stpAlterarClienteAgenda", nomeOrigemParameter, nomeDestinoParameter);
        }
    
        public virtual int stpComparaIndicacao()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stpComparaIndicacao");
        }
    
        public virtual int stpConverteAutor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stpConverteAutor");
        }
    
        public virtual int stpCorrigeIndicacao()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stpCorrigeIndicacao");
        }
    
        public virtual int stpEventos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stpEventos");
        }
    
        public virtual int stpExcluirProcessos(Nullable<int> idOrigem, Nullable<int> idDestino, string ids)
        {
            var idOrigemParameter = idOrigem.HasValue ?
                new ObjectParameter("IdOrigem", idOrigem) :
                new ObjectParameter("IdOrigem", typeof(int));
    
            var idDestinoParameter = idDestino.HasValue ?
                new ObjectParameter("IdDestino", idDestino) :
                new ObjectParameter("IdDestino", typeof(int));
    
            var idsParameter = ids != null ?
                new ObjectParameter("Ids", ids) :
                new ObjectParameter("Ids", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stpExcluirProcessos", idOrigemParameter, idDestinoParameter, idsParameter);
        }
    
        public virtual ObjectResult<stpFonesEmails_Result> stpFonesEmails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stpFonesEmails_Result>("stpFonesEmails");
        }
    
        public virtual int stpGeraFornecedoresNotasParcelas(Nullable<long> idNota)
        {
            var idNotaParameter = idNota.HasValue ?
                new ObjectParameter("IdNota", idNota) :
                new ObjectParameter("IdNota", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stpGeraFornecedoresNotasParcelas", idNotaParameter);
        }
    
        public virtual int stpRelatorioPorSede()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stpRelatorioPorSede");
        }
    
        public virtual ObjectResult<stpRelatorioProcessosSedes_Result> stpRelatorioProcessosSedes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stpRelatorioProcessosSedes_Result>("stpRelatorioProcessosSedes");
        }
    
        public virtual ObjectResult<stpRelatorioProfissao_Result> stpRelatorioProfissao()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stpRelatorioProfissao_Result>("stpRelatorioProfissao");
        }
    
        public virtual int stpVeProcessosSem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stpVeProcessosSem");
        }
    
        public virtual int stpVincularIndicacoes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stpVincularIndicacoes");
        }
    
        public virtual int stpRelatorioAgendaCancelamento_NaoCompareceu(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal, Nullable<System.DateTime> dataCancelamentoInicial, Nullable<System.DateTime> dataCancelamentoFinal, string tipo)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("DataInicial", dataInicial) :
                new ObjectParameter("DataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("DataFinal", dataFinal) :
                new ObjectParameter("DataFinal", typeof(System.DateTime));
    
            var dataCancelamentoInicialParameter = dataCancelamentoInicial.HasValue ?
                new ObjectParameter("DataCancelamentoInicial", dataCancelamentoInicial) :
                new ObjectParameter("DataCancelamentoInicial", typeof(System.DateTime));
    
            var dataCancelamentoFinalParameter = dataCancelamentoFinal.HasValue ?
                new ObjectParameter("DataCancelamentoFinal", dataCancelamentoFinal) :
                new ObjectParameter("DataCancelamentoFinal", typeof(System.DateTime));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stpRelatorioAgendaCancelamento_NaoCompareceu", dataInicialParameter, dataFinalParameter, dataCancelamentoInicialParameter, dataCancelamentoFinalParameter, tipoParameter);
        }
    
        [DbFunction("UranusEntities", "RelatorioCadastroClientes")]
        public virtual IQueryable<RelatorioCadastroClientes_Result> RelatorioCadastroClientes(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal, Nullable<int> usuario, Nullable<int> cliente, Nullable<int> profissao)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("dataInicial", dataInicial) :
                new ObjectParameter("dataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("dataFinal", dataFinal) :
                new ObjectParameter("dataFinal", typeof(System.DateTime));
    
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(int));
    
            var clienteParameter = cliente.HasValue ?
                new ObjectParameter("Cliente", cliente) :
                new ObjectParameter("Cliente", typeof(int));
    
            var profissaoParameter = profissao.HasValue ?
                new ObjectParameter("Profissao", profissao) :
                new ObjectParameter("Profissao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<RelatorioCadastroClientes_Result>("[UranusEntities].[RelatorioCadastroClientes](@dataInicial, @dataFinal, @Usuario, @Cliente, @Profissao)", dataInicialParameter, dataFinalParameter, usuarioParameter, clienteParameter, profissaoParameter);
        }
    
        public virtual int stpRelatorioClientesIndicacao()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stpRelatorioClientesIndicacao");
        }
    
        [DbFunction("UranusEntities", "PagarEmAbertoEmissao")]
        public virtual IQueryable<PagarEmAbertoEmissao_Result> PagarEmAbertoEmissao(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("dataInicial", dataInicial) :
                new ObjectParameter("dataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("dataFinal", dataFinal) :
                new ObjectParameter("dataFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<PagarEmAbertoEmissao_Result>("[UranusEntities].[PagarEmAbertoEmissao](@dataInicial, @dataFinal)", dataInicialParameter, dataFinalParameter);
        }
    
        [DbFunction("UranusEntities", "fnPagarRolPagamentos")]
        public virtual IQueryable<fnPagarRolPagamentos_Result> fnPagarRolPagamentos(Nullable<int> idEmpresa, Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("dataInicial", dataInicial) :
                new ObjectParameter("dataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("dataFinal", dataFinal) :
                new ObjectParameter("dataFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnPagarRolPagamentos_Result>("[UranusEntities].[fnPagarRolPagamentos](@IdEmpresa, @dataInicial, @dataFinal)", idEmpresaParameter, dataInicialParameter, dataFinalParameter);
        }
    
        [DbFunction("UranusEntities", "PagarEmAbertoVencimento")]
        public virtual IQueryable<PagarEmAbertoVencimento_Result> PagarEmAbertoVencimento(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("dataInicial", dataInicial) :
                new ObjectParameter("dataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("dataFinal", dataFinal) :
                new ObjectParameter("dataFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<PagarEmAbertoVencimento_Result>("[UranusEntities].[PagarEmAbertoVencimento](@dataInicial, @dataFinal)", dataInicialParameter, dataFinalParameter);
        }
    
        [DbFunction("UranusEntities", "PagarPagas")]
        public virtual IQueryable<PagarPagas_Result> PagarPagas(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("dataInicial", dataInicial) :
                new ObjectParameter("dataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("dataFinal", dataFinal) :
                new ObjectParameter("dataFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<PagarPagas_Result>("[UranusEntities].[PagarPagas](@dataInicial, @dataFinal)", dataInicialParameter, dataFinalParameter);
        }
    }
}
