//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesNotasServico
    {
        public int ID { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public Nullable<decimal> ValorServico { get; set; }
        public Nullable<decimal> PercentualIss { get; set; }
        public Nullable<decimal> ValorIss { get; set; }
        public string DescricaoServico { get; set; }
        public Nullable<int> NumeroParcelas { get; set; }
        public Nullable<int> Boleto { get; set; }
        public Nullable<System.DateTime> DataCacelamento { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Clientes Clientes { get; set; }
    }
}
