//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesNotasParcelas
    {
        public long Id { get; set; }
        public Nullable<long> IdClientesNota { get; set; }
        public Nullable<int> Parcela { get; set; }
        public Nullable<System.DateTime> Vencimento { get; set; }
        public Nullable<decimal> ValorParcela { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
        public Nullable<decimal> ValorPago { get; set; }
        public Nullable<decimal> Juros { get; set; }
        public Nullable<decimal> Descontos { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string Observacao { get; set; }
        public Nullable<int> LocalPagamento { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public bool Boleto { get; set; }
        public string Status { get; set; }
        public string NossoNumero { get; set; }
        public string Arquivo { get; set; }
        public Nullable<decimal> JurosDia { get; set; }
        public string LinhaDigitavel { get; set; }
        public string CODBARRAS { get; set; }
    
        public virtual ClientesNotas ClientesNotas { get; set; }
    }
}
