//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesOrcamentosOSServicos
    {
        public long ID { get; set; }
        public long IdOrcamentoOS { get; set; }
        public long IdServico { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<decimal> PrecoUnitario { get; set; }
        public Nullable<decimal> PrecoTotal { get; set; }
        public bool PrecoManual { get; set; }
    
        public virtual ClientesOrcamentosOS ClientesOrcamentosOS { get; set; }
        public virtual Servicos Servicos { get; set; }
    }
}
