//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.ClientesChamados = new HashSet<ClientesChamados>();
            this.ClientesEmails = new HashSet<ClientesEmails>();
            this.ClientesEnderecos = new HashSet<ClientesEnderecos>();
            this.ClientesFones = new HashSet<ClientesFones>();
            this.ClientesNotas = new HashSet<ClientesNotas>();
            this.ClientesTrocas = new HashSet<ClientesTrocas>();
            this.NotasServicos = new HashSet<NotasServicos>();
            this.CupomFiscal = new HashSet<CupomFiscal>();
            this.ClientesReclamacoes = new HashSet<ClientesReclamacoes>();
            this.ClientesHistoricos = new HashSet<ClientesHistoricos>();
            this.NotasFiscais = new HashSet<NotasFiscais>();
            this.ClientesOrcamentosOS = new HashSet<ClientesOrcamentosOS>();
            this.ClientesServicos = new HashSet<ClientesServicos>();
            this.ClientesOrcamentos = new HashSet<ClientesOrcamentos>();
            this.ClientesPedidos = new HashSet<ClientesPedidos>();
            this.ClientesContratos = new HashSet<ClientesContratos>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string TipoPessoa { get; set; }
        public string CpfCnpj { get; set; }
        public string InscricaoEstadual { get; set; }
        public string InscricaoMunicipal { get; set; }
        public string RG { get; set; }
        public string Cnae { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public string Status { get; set; }
        public string HomePage { get; set; }
        public Nullable<int> CodigoLegado { get; set; }
        public Nullable<int> EmpresaLegado { get; set; }
        public Nullable<bool> CreditoIcms { get; set; }
        public Nullable<bool> ConsumidorFinal { get; set; }
        public Nullable<int> ContribuinteIcms { get; set; }
    
        public virtual Vendedores Vendedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesChamados> ClientesChamados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesEmails> ClientesEmails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesEnderecos> ClientesEnderecos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesFones> ClientesFones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesNotas> ClientesNotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesTrocas> ClientesTrocas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasServicos> NotasServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CupomFiscal> CupomFiscal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesReclamacoes> ClientesReclamacoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesHistoricos> ClientesHistoricos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscais> NotasFiscais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesOrcamentosOS> ClientesOrcamentosOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesServicos> ClientesServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesOrcamentos> ClientesOrcamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesPedidos> ClientesPedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesContratos> ClientesContratos { get; set; }
    }
}
