//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesPedidosParcelas
    {
        public long ID { get; set; }
        public Nullable<long> IdPedido { get; set; }
        public Nullable<int> Prazo { get; set; }
        public Nullable<int> Parcela { get; set; }
        public Nullable<System.DateTime> Vencimento { get; set; }
        public Nullable<decimal> ValorParcela { get; set; }
        public bool Paga { get; set; }
        public bool Boleto { get; set; }
    
        public virtual ClientesPedidos ClientesPedidos { get; set; }
    }
}
