//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesTrocas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientesTrocas()
        {
            this.ClientesTrocaDevolucoes = new HashSet<ClientesTrocaDevolucoes>();
            this.ClientesTrocaVendas = new HashSet<ClientesTrocaVendas>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public Nullable<decimal> TotalDevolucao { get; set; }
        public Nullable<decimal> TotalVenda { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<long> NumeroPedido { get; set; }
        public string Observacao { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesTrocaDevolucoes> ClientesTrocaDevolucoes { get; set; }
        public virtual Vendedores Vendedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesTrocaVendas> ClientesTrocaVendas { get; set; }
        public virtual Empresas Empresas { get; set; }
    }
}
