//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FornecedoresCotacoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FornecedoresCotacoes()
        {
            this.FornecedoresCotacoesProdutos = new HashSet<FornecedoresCotacoesProdutos>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public int IdFornecedor { get; set; }
        public int NumeroCotacao { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<System.DateTime> DataEntrada { get; set; }
        public string Transportadora { get; set; }
        public string ConicoesPagamento { get; set; }
    
        public virtual Fornecedores Fornecedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornecedoresCotacoesProdutos> FornecedoresCotacoesProdutos { get; set; }
        public virtual Empresas Empresas { get; set; }
    }
}
