//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FornecedoresOrdemComprasProdutos
    {
        public int ID { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public int IdOrdemCompra { get; set; }
        public Nullable<long> IdProdutosFornecedor { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> QuantidadePedida { get; set; }
        public Nullable<decimal> QuantidadeRecebida { get; set; }
        public Nullable<decimal> PrecoUnitario { get; set; }
        public Nullable<decimal> PercentualIpi { get; set; }
        public Nullable<decimal> ValorIpi { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual FornecedoresOrdemCompras FornecedoresOrdemCompras { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual ProdutosFornecedores ProdutosFornecedores { get; set; }
    }
}
