//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasFiscaisServicos
    {
        public long Id { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<long> IdOrdemServico { get; set; }
        public Nullable<long> NumeroOS { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string DescricaoServico { get; set; }
        public Nullable<decimal> ValorServiço { get; set; }
        public Nullable<decimal> PercentualIssqn { get; set; }
        public Nullable<decimal> ValorIssqn { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual ClientesServicos ClientesServicos { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual Status Status { get; set; }
    }
}
