//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasImportacao
    {
        public long Id { get; set; }
        public string NumeroNota { get; set; }
        public Nullable<System.DateTime> DataProcessamento { get; set; }
        public Nullable<System.DateTime> DataNota { get; set; }
        public string Fornecedor { get; set; }
        public Nullable<decimal> TotalNota { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    
        public virtual Empresas Empresas { get; set; }
    }
}
