//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasServicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotasServicos()
        {
            this.NotasServicosParcelas = new HashSet<NotasServicosParcelas>();
        }
    
        public long Id { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<long> NumeroNota { get; set; }
        public Nullable<long> IdOrdemServico { get; set; }
        public Nullable<long> NumeroOS { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<long> IdClienteEndereco { get; set; }
        public Nullable<int> IdClienteEmail { get; set; }
        public string DescricaoServico { get; set; }
        public Nullable<decimal> ValorServico { get; set; }
        public Nullable<int> PercentualIssqn { get; set; }
        public Nullable<decimal> ValorIssqn { get; set; }
        public Nullable<int> Plano { get; set; }
        public Nullable<int> LocalPagamento { get; set; }
        public string Observacao { get; set; }
        public Nullable<int> IdFormaPagamento { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual ClientesEmails ClientesEmails { get; set; }
        public virtual ClientesEnderecos ClientesEnderecos { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasServicosParcelas> NotasServicosParcelas { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual ClientesServicos ClientesServicos { get; set; }
    }
}
