//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatorioProdutos
    {
        public long ID { get; set; }
        public string Codigo { get; set; }
        public string Referencia { get; set; }
        public string Nome { get; set; }
        public decimal Quantidade1 { get; set; }
        public decimal Quantidade2 { get; set; }
        public Nullable<decimal> PrecoVenda { get; set; }
        public string Path { get; set; }
    }
}
