//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Suite.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uranus.Suite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cabecalho {
            get {
                object obj = ResourceManager.GetObject("cabecalho", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;img alt=&quot;&quot; src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAlMAAABuCAYAAAADOpayAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAB3RSURBVHhe7d0HfBTV2gbwF0joCVIDkaoiTUS4NAXpEJASykeRJojCvQj6WQAVLKCgiKKXegFF4VpApPdeEkLvTWro0pEkQOgfz7tnkt3NtrAS8snz97e/nTk72TLZMI/vOXMmzZ27hIiIiIjuSVpzT0RERET3gGGKiIiIyA8MU0RERER+YJgiIiIi8gPDFBEREZEfGKaIiIiI/MAwRUREROQHhikiIiIiPzBMEREREfmBYYqIiIjIDwxTRERERH5gmCIiIiLyA8MUERERkR8YpoiIiIj8kObOXWaZ6KHGP4UH48qVK9KmdRsZNXqU5M+f37T6ZvSo0RIXFye9evcyLZSS0qRJY5aIHm6sT [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string cabeçalho {
            get {
                return ResourceManager.GetString("cabeçalho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rodape {
            get {
                object obj = ResourceManager.GetObject("rodape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;    
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///    &lt;div style=&quot;font-size:12px; font-family:Arial; text-align:justify; margin-left:40px; margin-right: 40px;&quot;&gt;
        ///        &lt;p&gt;
        ///            &lt;br /&gt;
        ///        &lt;p style=&quot;text-align:center&quot;&gt;&lt;b&gt;MM. JU&amp;Iacute;ZO DA #VaraNumero VARA FEDERAL DE #VaraCidade&lt;/b&gt;&lt;/p&gt;
        ///        &lt;br /&gt;
        ///        &lt;br /&gt;
        ///        &lt;br /&gt;
        ///        &lt;br /&gt;
        ///        &lt;br /&gt;&lt;b&gt;#ClienteNome&lt;/b&gt;, #ClienteNacionalidade, #ClienteEs [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string TemplateInicialAposentadoria {
            get {
                return ResourceManager.GetString("TemplateInicialAposentadoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 
        ///&lt;table style=&quot;width:100%; border-collapse:collapse; border-width:1px; border-color:black; border-style: solid;&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td style=&quot;border-collapse:collapse; border-width:1px; border-color:black; border-style: solid;&quot;&gt;
        ///            Periodo
        ///        &lt;/td&gt;
        ///        &lt;td style=&quot;border-collapse:collapse; border-width:1px; border-color:black; border-style: solid;&quot;&gt;
        ///            #Periodo
        ///        &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///        &lt;td style=&quot;border-collapse:collapse; border-width:1px; border-color:bl [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string TemplateInicialAposentadoriaQuadro {
            get {
                return ResourceManager.GetString("TemplateInicialAposentadoriaQuadro", resourceCulture);
            }
        }
    }
}
