//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendasMassaHistorico
    {
        public int Id { get; set; }
        public int IdAgendaMassa { get; set; }
        public string Data { get; set; }
        public string Hora { get; set; }
        public string Sede { get; set; }
        public string Sala { get; set; }
        public string Profissional { get; set; }
        public string Status { get; set; }
        public Nullable<int> IdAgenda { get; set; }
    
        public virtual AgendasMassa AgendasMassa { get; set; }
    }
}
