//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agendas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agendas()
        {
            this.PreAgendamento = new HashSet<PreAgendamento>();
        }
    
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public string Hora { get; set; }
        public int IdTipo { get; set; }
        public int IdSede { get; set; }
        public Nullable<int> IdSala { get; set; }
        public int IdProfissional { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<decimal> ValorConsulta { get; set; }
        public string MotivoConsulta { get; set; }
        public int IdUsuario { get; set; }
        public string Encaixe { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string NomeUsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public string NomeUsuarioAlteracao { get; set; }
        public Nullable<bool> Compareceu { get; set; }
        public Nullable<bool> Cancelou { get; set; }
        public Nullable<System.DateTime> DataCancelamento { get; set; }
        public Nullable<int> IdFormaPagamento { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<long> IdReceita { get; set; }
        public Nullable<int> IdArea { get; set; }
    
        public virtual AgendasTipos AgendasTipos { get; set; }
        public virtual Bancos Bancos { get; set; }
        public virtual FormaPagamentos FormaPagamentos { get; set; }
        public virtual Salas Salas { get; set; }
        public virtual Sedes Sedes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreAgendamento> PreAgendamento { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Profissionais Profissionais { get; set; }
    }
}
