//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alertas
    {
        public long Id { get; set; }
        public System.DateTime DataHora { get; set; }
        public int IdUsuario { get; set; }
        public string Mensagem { get; set; }
        public bool Lido { get; set; }
        public string NumeroProcesso { get; set; }
        public Nullable<int> IdAcao { get; set; }
        public Nullable<int> IdPessoa { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
