//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caixas
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> IdHistorico { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> ValorDebito { get; set; }
        public Nullable<decimal> ValorCredito { get; set; }
        public Nullable<int> IdOrigem { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string NomeUsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public string NomeUsuarioAlteracao { get; set; }
    
        public virtual Historicos Historicos { get; set; }
    }
}
