//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesNotasPagamentos
    {
        public long Id { get; set; }
        public Nullable<long> IdClienteNota { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
        public Nullable<decimal> ValorPago { get; set; }
        public Nullable<decimal> Juros { get; set; }
        public Nullable<decimal> Desconto { get; set; }
        public string Observacao { get; set; }
        public Nullable<int> IdDestino { get; set; }
        public Nullable<int> IdFormaPagamento { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string NomeUsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public string NomeUsuarioAlteracao { get; set; }
    
        public virtual ClientesNotas ClientesNotas { get; set; }
    }
}
