//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesFinanceiroParametrizacoes
    {
        public long Id { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<decimal> Caixa { get; set; }
        public Nullable<decimal> PercentualNF { get; set; }
        public Nullable<int> IdProfissional { get; set; }
        public Nullable<int> IdIndicacao1 { get; set; }
        public Nullable<decimal> PercentualIdIndicacao1 { get; set; }
        public Nullable<int> IdIndicacao2 { get; set; }
        public Nullable<decimal> PercentualIdIndicacao2 { get; set; }
        public string TipoComissao { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
