//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.FornecedoresContratos = new HashSet<FornecedoresContratos>();
            this.NotasServicos = new HashSet<NotasServicos>();
            this.FornecedoresNotas = new HashSet<FornecedoresNotas>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Cep { get; set; }
        public string Cnpj { get; set; }
        public string InscricaoEstadual { get; set; }
        public string Fone { get; set; }
        public string Cnae { get; set; }
        public string InscricaoMunicipal { get; set; }
        public string CodigoMunicipio { get; set; }
        public string Regime { get; set; }
        public Nullable<bool> HorarioVerao { get; set; }
        public string Icms { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public string Ambiente { get; set; }
        public string TokenHomologacao { get; set; }
        public string TokenProducao { get; set; }
        public string Url_homologacao { get; set; }
        public string Url_Producao { get; set; }
        public string PastaNotas { get; set; }
        public string SMTPEndereco { get; set; }
        public string SMTPRemetente { get; set; }
        public string SMTPUsuario { get; set; }
        public string SMTPSenha { get; set; }
        public string SMTPPorta { get; set; }
        public Nullable<long> Nossonumero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornecedoresContratos> FornecedoresContratos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasServicos> NotasServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornecedoresNotas> FornecedoresNotas { get; set; }
    }
}
