//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceiroDespesas
    {
        public long Id { get; set; }
        public Nullable<int> IdOrigem { get; set; }
        public string NumeroDocumento { get; set; }
        public Nullable<System.DateTime> DataDocumento { get; set; }
        public Nullable<int> IdFinanceiroTipo { get; set; }
        public Nullable<int> IdCentroCusto { get; set; }
        public Nullable<int> IdFornecedor { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
        public string Observacao { get; set; }
        public Nullable<long> IdPagar { get; set; }
        public Nullable<long> IdCaixa { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<long> IdBancosLancamento { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string NomeUsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public string NomeUsuarioAlteracao { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        public virtual FinanceiroTipo FinanceiroTipo { get; set; }
        public virtual Fornecedores Fornecedores { get; set; }
        public virtual Sedes Sedes { get; set; }
        public virtual FinanceiroOrigem FinanceiroOrigem { get; set; }
    }
}
