//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceiroReceitas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinanceiroReceitas()
        {
            this.NotasServicos1 = new HashSet<NotasServicos>();
        }
    
        public long Id { get; set; }
        public Nullable<int> IdOrigem { get; set; }
        public string NumeroDocumento { get; set; }
        public System.DateTime DataDocumento { get; set; }
        public Nullable<int> IdFinanceiroTipo { get; set; }
        public Nullable<int> IdCentroCusto { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
        public string Observacao { get; set; }
        public Nullable<long> IdReceber { get; set; }
        public Nullable<long> IdCaixa { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<long> IdBancosLancamento { get; set; }
        public Nullable<bool> Nota { get; set; }
        public Nullable<long> IdNota { get; set; }
        public Nullable<decimal> ValorBruto { get; set; }
        public Nullable<decimal> IRRetido { get; set; }
        public Nullable<decimal> Desconto { get; set; }
        public Nullable<int> IdProcessoAcao { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string NomeUsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public string NomeUsuarioAlteracao { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual FinanceiroOrigem FinanceiroOrigem { get; set; }
        public virtual FinanceiroTipo FinanceiroTipo { get; set; }
        public virtual NotasServicos NotasServicos { get; set; }
        public virtual ProcessosAcoes ProcessosAcoes { get; set; }
        public virtual ProcessosAreas ProcessosAreas { get; set; }
        public virtual Sedes Sedes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasServicos> NotasServicos1 { get; set; }
        public virtual ProcessosAreas ProcessosAreas1 { get; set; }
    }
}
