//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FornecedoresNotas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FornecedoresNotas()
        {
            this.FornecedoresNotasParcelas = new HashSet<FornecedoresNotasParcelas>();
        }
    
        public long Id { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdFornecedor { get; set; }
        public string NumeroDocumento { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Plano { get; set; }
        public Nullable<decimal> ValorParcela { get; set; }
        public Nullable<int> IdFormaPagamento { get; set; }
        public string Observacao { get; set; }
        public Nullable<System.DateTime> PrimeiroVencimento { get; set; }
        public Nullable<int> IdContrato { get; set; }
        public Nullable<int> IdAcao { get; set; }
        public Nullable<int> IdSede { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string NomeUsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public string NomeUsuarioAlteracao { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Fornecedores Fornecedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornecedoresNotasParcelas> FornecedoresNotasParcelas { get; set; }
        public virtual FormaPagamentos FormaPagamentos { get; set; }
    }
}
