//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FornecedoresContratos
    {
        public int ID { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdFornecedor { get; set; }
        public string Objeto { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public Nullable<int> Meses { get; set; }
        public Nullable<decimal> ValorMensal { get; set; }
    
        public virtual Fornecedores Fornecedores { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
