//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoasUsuariosAplicativo
    {
        public int Id { get; set; }
        public Nullable<int> IdPessoa { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
    
        public virtual Pessoas Pessoas { get; set; }
    }
}
