//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoasSolicitacoes
    {
        public int Id { get; set; }
        public int IdContrato { get; set; }
        public Nullable<System.DateTime> DataSolicitacao { get; set; }
        public Nullable<System.DateTime> DataAprovacao { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<int> Dias { get; set; }
        public string Justificativa { get; set; }
    
        public virtual Pessoas Pessoas { get; set; }
    }
}
