//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoasAusencias
    {
        public int Id { get; set; }
        public int IdPessoa { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public Nullable<bool> Abonado { get; set; }
        public string Observacao { get; set; }
    
        public virtual Pessoas Pessoas { get; set; }
    }
}
