//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pessoas()
        {
            this.PessoasUsuariosAplicativo = new HashSet<PessoasUsuariosAplicativo>();
            this.Email = new HashSet<Email>();
            this.Fones = new HashSet<Fones>();
            this.PessoasAvaliacoes = new HashSet<PessoasAvaliacoes>();
            this.PessoasContratos = new HashSet<PessoasContratos>();
            this.PessoasDocumentos = new HashSet<PessoasDocumentos>();
            this.PessoasFerias = new HashSet<PessoasFerias>();
            this.Clientes = new HashSet<Clientes>();
            this.Profissionais = new HashSet<Profissionais>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string NomeBusca { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string CodigoMunicipio { get; set; }
        public string Municipio { get; set; }
        public string Estado { get; set; }
        public string Cep { get; set; }
        public string RG { get; set; }
        public string CpfCnpj { get; set; }
        public Nullable<int> IDLegado { get; set; }
        public string LegadoFones { get; set; }
        public string LegadoEmail { get; set; }
        public string DataNascimento { get; set; }
        public string EstadoCivil { get; set; }
        public string NomeMae { get; set; }
        public Nullable<bool> Cliente { get; set; }
        public string LGPDAutorizado { get; set; }
        public Nullable<bool> Etiqueta { get; set; }
        public string NomeUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoasUsuariosAplicativo> PessoasUsuariosAplicativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email> Email { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fones> Fones { get; set; }
        public virtual PessoasAusencias PessoasAusencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoasAvaliacoes> PessoasAvaliacoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoasContratos> PessoasContratos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoasDocumentos> PessoasDocumentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoasFerias> PessoasFerias { get; set; }
        public virtual PessoasSolicitacoes PessoasSolicitacoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profissionais> Profissionais { get; set; }
    }
}
