//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessosAcoesEventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcessosAcoesEventos()
        {
            this.ProcessosAgendaProfissional = new HashSet<ProcessosAgendaProfissional>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdProcessosAcao { get; set; }
        public Nullable<int> IdProcessosEvento { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> PrazoEvento1 { get; set; }
        public Nullable<System.DateTime> PrazoEvento2 { get; set; }
        public Nullable<long> IdProcessosEventoPendente { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> UsuarioLegado { get; set; }
        public Nullable<System.DateTime> DataCumprimentoPrazo { get; set; }
        public string Resumo { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public Nullable<int> IdUsuarioAlteracao { get; set; }
        public string NomeBusca { get; set; }
    
        public virtual ProcessosAcoes ProcessosAcoes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessosAgendaProfissional> ProcessosAgendaProfissional { get; set; }
        public virtual ProcessosEventos ProcessosEventos { get; set; }
    }
}
