//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessosAcoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcessosAcoes()
        {
            this.ProcessosAcoesEventos = new HashSet<ProcessosAcoesEventos>();
            this.ClientesNotas = new HashSet<ClientesNotas>();
            this.FinanceiroReceitas = new HashSet<FinanceiroReceitas>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdProcesso { get; set; }
        public Nullable<System.DateTime> DataAcao { get; set; }
        public Nullable<int> IdAcao { get; set; }
        public Nullable<int> IdVara { get; set; }
        public Nullable<int> IdProcessosArea { get; set; }
        public string NumeroProcesso { get; set; }
        public string Sigla { get; set; }
        public string NumeroProcessoAntigo { get; set; }
        public Nullable<bool> EventoAutomatico { get; set; }
        public string Status { get; set; }
    
        public virtual Processos Processos { get; set; }
        public virtual ProcessosCadastroAcao ProcessosCadastroAcao { get; set; }
        public virtual ProcessosAcoes ProcessosAcoes1 { get; set; }
        public virtual ProcessosAcoes ProcessosAcoes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessosAcoesEventos> ProcessosAcoesEventos { get; set; }
        public virtual ProcessosAreas ProcessosAreas { get; set; }
        public virtual ProcessosVara ProcessosVara { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesNotas> ClientesNotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinanceiroReceitas> FinanceiroReceitas { get; set; }
    }
}
