//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Processos()
        {
            this.ProcessosPartes = new HashSet<ProcessosPartes>();
            this.ProcessosAcoes = new HashSet<ProcessosAcoes>();
            this.ProcessosAutores = new HashSet<ProcessosAutores>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DataInclusao { get; set; }
        public Nullable<int> IdProfissionalResponsavel { get; set; }
        public string Objeto { get; set; }
        public string Status { get; set; }
        public string Observacao { get; set; }
        public Nullable<int> Ficha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessosPartes> ProcessosPartes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessosAcoes> ProcessosAcoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessosAutores> ProcessosAutores { get; set; }
        public virtual Profissionais Profissionais { get; set; }
    }
}
