//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessosPartes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcessosPartes()
        {
            this.ProcessosPartesAdvogados = new HashSet<ProcessosPartesAdvogados>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdProcesso { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string NomeParte { get; set; }
    
        public virtual Processos Processos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessosPartesAdvogados> ProcessosPartesAdvogados { get; set; }
        public virtual Clientes Clientes { get; set; }
    }
}
