//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessosAgendaProfissional
    {
        public int ID { get; set; }
        public Nullable<int> IdProfissional { get; set; }
        public Nullable<int> IdProcessosEvento { get; set; }
        public bool Excluido { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string NomeUsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public string NomeUsuarioAlteracao { get; set; }
        public Nullable<int> IdNovoEvento { get; set; }
    
        public virtual ProcessosAcoesEventos ProcessosAcoesEventos { get; set; }
        public virtual Profissionais Profissionais { get; set; }
    }
}
