//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfissionaisPeriodosAquisitivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfissionaisPeriodosAquisitivo()
        {
            this.ProfissionaisSolicitacoes = new HashSet<ProfissionaisSolicitacoes>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdProfissional { get; set; }
        public Nullable<int> IdContrato { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<int> DiasGozados { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string UsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public string UsuarioAlteracao { get; set; }
    
        public virtual ProfissionaisContratos ProfissionaisContratos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfissionaisSolicitacoes> ProfissionaisSolicitacoes { get; set; }
        public virtual Profissionais Profissionais { get; set; }
    }
}
