//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfissionaisContratos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfissionaisContratos()
        {
            this.ProfissionaisPeriodosAquisitivo = new HashSet<ProfissionaisPeriodosAquisitivo>();
            this.ProfissionaisSolicitacoes = new HashSet<ProfissionaisSolicitacoes>();
            this.ProfissionaisFerias = new HashSet<ProfissionaisFerias>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdProfissional { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public string TipoContrato { get; set; }
        public Nullable<int> IdSede { get; set; }
        public string PDFPath { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string UsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public string UsuarioAlteracao { get; set; }
    
        public virtual Sedes Sedes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfissionaisPeriodosAquisitivo> ProfissionaisPeriodosAquisitivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfissionaisSolicitacoes> ProfissionaisSolicitacoes { get; set; }
        public virtual Profissionais Profissionais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfissionaisFerias> ProfissionaisFerias { get; set; }
    }
}
