//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfissionaisAvaliacoes
    {
        public int Id { get; set; }
        public Nullable<int> IdProfissional { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Avaliador { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string UsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public string UsuarioAlteracao { get; set; }
    
        public virtual Profissionais Profissionais { get; set; }
    }
}
