//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfissionaisSolicitacoes
    {
        public int Id { get; set; }
        public Nullable<int> IdProfissional { get; set; }
        public Nullable<int> IdContrato { get; set; }
        public Nullable<System.DateTime> DataSolicitacao { get; set; }
        public Nullable<System.DateTime> DataAprovacao { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<int> Saldo { get; set; }
        public Nullable<int> Dias { get; set; }
        public string Justificativa { get; set; }
        public Nullable<int> IdPeriodoAquisitivo { get; set; }
        public Nullable<bool> SolicitacaoEspecial { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string UsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public string UsuarioAlteracao { get; set; }
    
        public virtual ProfissionaisContratos ProfissionaisContratos { get; set; }
        public virtual ProfissionaisPeriodosAquisitivo ProfissionaisPeriodosAquisitivo { get; set; }
        public virtual Profissionais Profissionais { get; set; }
    }
}
