//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RHCargosNiveis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RHCargosNiveis()
        {
            this.RHCargosSalarios = new HashSet<RHCargosSalarios>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdCargo { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Atribuicoes { get; set; }
        public Nullable<int> IdResponsavel { get; set; }
        public Nullable<int> IdProximoCargo { get; set; }
        public Nullable<int> IdAreaResponsavel { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string UsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public string UsuarioAlteracao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RHCargosSalarios> RHCargosSalarios { get; set; }
    }
}
