//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatesIniciaisAposentadoriaPeriodos
    {
        public int IDPeriodo { get; set; }
        public Nullable<int> IDTemplate { get; set; }
        public string Periodo { get; set; }
        public string Empresa { get; set; }
        public string Atividades { get; set; }
        public string EnquadramentoLegal { get; set; }
        public string Provas { get; set; }
        public string ProvasAProduzir { get; set; }
        public string OBS { get; set; }
    
        public virtual TemplatesIniciaisAposentadoria TemplatesIniciaisAposentadoria { get; set; }
    }
}
