//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatesIniciaisAposentadoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplatesIniciaisAposentadoria()
        {
            this.TemplatesIniciaisAposentadoriaPeriodos = new HashSet<TemplatesIniciaisAposentadoriaPeriodos>();
        }
    
        public int IdTemplate { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<int> IdProfissional { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string NomeUsuarioCadastro { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public string NomeUsuarioAlteracao { get; set; }
        public string VaraNumero { get; set; }
        public string VaraCidade { get; set; }
        public string ProcessoDataProtocolo { get; set; }
        public string RequerimentoNumero { get; set; }
        public string ProcessoAtividade { get; set; }
        public Nullable<bool> ProcessoReafirmacaoDER { get; set; }
        public Nullable<bool> ProcessoGratuidade { get; set; }
        public string ProcessoValorCausa { get; set; }
        public string ProcessoRodapeData { get; set; }
        public string ProcessoAdvogado { get; set; }
        public string ProcessoImagem { get; set; }
        public string ProcessoOAB { get; set; }
        public string ProcessoResumoPeriodo { get; set; }
        public string ProcessoResumoPeriodosDER { get; set; }
        public string ClienteNome { get; set; }
        public string ClienteNacionalidade { get; set; }
        public string ClienteEstadoCivil { get; set; }
        public string ClienteProfissao { get; set; }
        public string ClienteCPF { get; set; }
        public string ClienteEndereco { get; set; }
        public string ClienteBairro { get; set; }
        public string ClienteCidade { get; set; }
        public string ClienteEstado { get; set; }
        public string ClienteCep { get; set; }
        public string ClienteEmail { get; set; }
        public string ProcessoExcel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplatesIniciaisAposentadoriaPeriodos> TemplatesIniciaisAposentadoriaPeriodos { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Profissionais Profissionais { get; set; }
    }
}
