//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uranus.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Processos_Financeiros
    {
        public int IdCliente { get; set; }
        public int IdPessoa { get; set; }
        public string NomePessoa { get; set; }
        public Nullable<long> NumeroDocumento { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public Nullable<int> Parcela { get; set; }
        public Nullable<System.DateTime> Vencimento { get; set; }
        public Nullable<decimal> ValorParcela { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
    }
}
