//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bancos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bancos()
        {
            this.BancosLancamentos = new HashSet<BancosLancamentos>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public Nullable<int> NumeroBanco { get; set; }
        public string Agencia { get; set; }
        public string Conta { get; set; }
        public string Convenio { get; set; }
        public string Carteira { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BancosLancamentos> BancosLancamentos { get; set; }
    }
}
