//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesTrocaDevolucoes
    {
        public int Id { get; set; }
        public Nullable<int> IdTroca { get; set; }
        public Nullable<long> IdProduto { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public Nullable<decimal> PrecoUnitario { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> Defeito { get; set; }
        public string Descricao { get; set; }
    
        public virtual ClientesTrocas ClientesTrocas { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
