//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesServicosProdutos
    {
        public long ID { get; set; }
        public long IdOrdemServico { get; set; }
        public long IdProduto { get; set; }
        public long IdProdutoFornecedor { get; set; }
        public string Descricao { get; set; }
        public string Unidade { get; set; }
        public string ST { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public Nullable<decimal> PrecoUnitario { get; set; }
        public Nullable<decimal> PercentualIPI { get; set; }
        public Nullable<decimal> ValorIPI { get; set; }
        public Nullable<decimal> PercentualDesconto { get; set; }
        public Nullable<decimal> ValorDesconto { get; set; }
        public Nullable<decimal> PrecoTotal { get; set; }
        public Nullable<decimal> Devolucao { get; set; }
        public Nullable<decimal> BaseCalculo { get; set; }
        public Nullable<decimal> PercentualReducaoBC { get; set; }
        public Nullable<decimal> PercentualICMS { get; set; }
        public Nullable<decimal> ValorICMS { get; set; }
        public Nullable<decimal> Custo { get; set; }
        public string NCM { get; set; }
        public Nullable<decimal> MVA { get; set; }
        public Nullable<decimal> BaseST { get; set; }
        public Nullable<decimal> PercentualST { get; set; }
        public Nullable<decimal> ValorICMSST { get; set; }
        public Nullable<decimal> ReducaoST { get; set; }
        public bool PrecoManual { get; set; }
        public string TipoComissao { get; set; }
        public string Observacao { get; set; }
    
        public virtual ClientesServicos ClientesServicos { get; set; }
        public virtual ProdutosFornecedores ProdutosFornecedores { get; set; }
    }
}
