//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesPedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientesPedidos()
        {
            this.NotasFiscais = new HashSet<NotasFiscais>();
            this.ProdutosEstoques = new HashSet<ProdutosEstoques>();
            this.ClientesPedidosParcelas = new HashSet<ClientesPedidosParcelas>();
            this.NotasFiscaisPedidos = new HashSet<NotasFiscaisPedidos>();
            this.ClientesPedidosProdutos = new HashSet<ClientesPedidosProdutos>();
        }
    
        public long ID { get; set; }
        public int IdEmpresa { get; set; }
        public long NumeroPedido { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string ConsumidorFinal { get; set; }
        public Nullable<decimal> TotalPedido { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<long> IdClienteEndereco { get; set; }
        public Nullable<int> IdProfissional { get; set; }
        public Nullable<int> ContribuinteIcms { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public Nullable<int> IdVendedor1 { get; set; }
        public string OrdemCompra { get; set; }
        public Nullable<int> Plano { get; set; }
        public Nullable<decimal> Comissao { get; set; }
        public Nullable<decimal> TotalPecas { get; set; }
        public Nullable<decimal> ValorMaoObra { get; set; }
        public Nullable<decimal> PercentualDesconto { get; set; }
        public Nullable<decimal> TotalDesconto { get; set; }
        public Nullable<decimal> TotalLiquido { get; set; }
        public Nullable<decimal> TotalCusto { get; set; }
        public Nullable<decimal> TotalIPI { get; set; }
        public Nullable<decimal> TotalBaseCalculo { get; set; }
        public Nullable<decimal> TotalICMS { get; set; }
        public Nullable<decimal> TotalBaseST { get; set; }
        public Nullable<decimal> TotalICMSST { get; set; }
        public Nullable<decimal> MargemLucro { get; set; }
        public Nullable<int> IdTransportadora { get; set; }
        public Nullable<decimal> Frete { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string Observacao { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<long> NumeroOrcamento { get; set; }
        public string NotaFiscal { get; set; }
        public Nullable<long> IdClientesOrcamento { get; set; }
        public Nullable<long> IdClientesOrcamentoOS { get; set; }
        public Nullable<int> IdCondicaoPagamento { get; set; }
        public Nullable<int> IdFormaPagamento { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
        public string Nota { get; set; }
        public string NumeroCupom { get; set; }
        public string VendedorLegado { get; set; }
        public Nullable<decimal> TotalDescontoPecas { get; set; }
        public Nullable<bool> ParcelaManual { get; set; }
        public Nullable<bool> PrecoRevenda { get; set; }
        public Nullable<int> LocalPagamento { get; set; }
        public Nullable<int> IdBanco { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual ClientesEnderecos ClientesEnderecos { get; set; }
        public virtual ClientesOrcamentos ClientesOrcamentos { get; set; }
        public virtual ClientesOrcamentosOS ClientesOrcamentosOS { get; set; }
        public virtual CondicoesPagamentos CondicoesPagamentos { get; set; }
        public virtual FormaPagamentos FormaPagamentos { get; set; }
        public virtual Profissionais Profissionais { get; set; }
        public virtual Vendedores Vendedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscais> NotasFiscais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutosEstoques> ProdutosEstoques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesPedidosParcelas> ClientesPedidosParcelas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscaisPedidos> NotasFiscaisPedidos { get; set; }
        public virtual Empresas Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesPedidosProdutos> ClientesPedidosProdutos { get; set; }
        public virtual Status Status { get; set; }
        public virtual Transportadoras Transportadoras { get; set; }
    }
}
