//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesEmails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientesEmails()
        {
            this.NotasServicos = new HashSet<NotasServicos>();
            this.NotasFiscais = new HashSet<NotasFiscais>();
        }
    
        public int ID { get; set; }
        public int IDCliente { get; set; }
        public string Email { get; set; }
        public bool Ativo { get; set; }
        public Nullable<int> Score { get; set; }
        public bool Principal { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual ClientesEmails ClientesEmails1 { get; set; }
        public virtual ClientesEmails ClientesEmails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasServicos> NotasServicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscais> NotasFiscais { get; set; }
    }
}
