//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesContratos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientesContratos()
        {
            this.ClientesContratosParcelas = new HashSet<ClientesContratosParcelas>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdArea { get; set; }
        public string Objeto { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public Nullable<int> Meses { get; set; }
        public Nullable<decimal> ValorMensal { get; set; }
        public Nullable<int> Vendedor { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Empresas Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesContratosParcelas> ClientesContratosParcelas { get; set; }
    }
}
