//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesFones
    {
        public int ID { get; set; }
        public Nullable<int> IDCliente { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> DDD { get; set; }
        public string Numero { get; set; }
        public string Ramal { get; set; }
        public string CF { get; set; }
        public string HorarioInicio { get; set; }
        public string HorarioFim { get; set; }
        public string Contato { get; set; }
        public string Observacao { get; set; }
        public Nullable<int> Score { get; set; }
        public string Status { get; set; }
        public Nullable<bool> SMS { get; set; }
        public Nullable<bool> Whatsapp { get; set; }
        public bool Principal { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
