//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FornecedoresCotacoesProdutos
    {
        public int ID { get; set; }
        public int IdFornecedorCotacao { get; set; }
        public long IdProdutoFornecedor { get; set; }
        public string Descricao { get; set; }
        public Nullable<decimal> Qunatidade { get; set; }
        public Nullable<decimal> PrecoUnitario { get; set; }
        public Nullable<decimal> PercentualIPI { get; set; }
        public Nullable<decimal> ValorIpi { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual FornecedoresCotacoes FornecedoresCotacoes { get; set; }
        public virtual ProdutosFornecedores ProdutosFornecedores { get; set; }
    }
}
