//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornecedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fornecedores()
        {
            this.FornecedoresCotacoes = new HashSet<FornecedoresCotacoes>();
            this.FornecedoresNotasEntradas = new HashSet<FornecedoresNotasEntradas>();
            this.FornecedoresOrdemCompras = new HashSet<FornecedoresOrdemCompras>();
            this.FornecedoresNotasEntradas1 = new HashSet<FornecedoresNotasEntradas>();
            this.NotasFiscais = new HashSet<NotasFiscais>();
            this.FornecedoresEmail = new HashSet<FornecedoresEmail>();
            this.FornecedoresFones = new HashSet<FornecedoresFones>();
            this.ProdutosFornecedores = new HashSet<ProdutosFornecedores>();
            this.FornecedoresContratos = new HashSet<FornecedoresContratos>();
            this.FornecedoresLancamentos = new HashSet<FornecedoresLancamentos>();
            this.FornecedoresNotas = new HashSet<FornecedoresNotas>();
        }
    
        public int ID { get; set; }
        public string TipoPessoa { get; set; }
        public string CpfCnpj { get; set; }
        public string Nome { get; set; }
        public string NomeFantasia { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<long> RG { get; set; }
        public string InscricaoEstadual { get; set; }
        public string InscricaoMunicipal { get; set; }
        public string Cnae { get; set; }
        public string Vendedor { get; set; }
        public Nullable<decimal> LimiteCredito { get; set; }
        public Nullable<bool> Estrangeiro { get; set; }
        public string Cep { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string CodigoMunicipio { get; set; }
        public string Municipio { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string BancoNumero { get; set; }
        public string AgenciaNumero { get; set; }
        public string ContaNumero { get; set; }
        public string HomePage { get; set; }
        public Nullable<int> CodigoLegado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornecedoresCotacoes> FornecedoresCotacoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornecedoresNotasEntradas> FornecedoresNotasEntradas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornecedoresOrdemCompras> FornecedoresOrdemCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornecedoresNotasEntradas> FornecedoresNotasEntradas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscais> NotasFiscais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornecedoresEmail> FornecedoresEmail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornecedoresFones> FornecedoresFones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutosFornecedores> ProdutosFornecedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornecedoresContratos> FornecedoresContratos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornecedoresLancamentos> FornecedoresLancamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FornecedoresNotas> FornecedoresNotas { get; set; }
    }
}
