//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class FornecedoresLancamentosParcelas
    {
        public long Id { get; set; }
        public Nullable<long> IdLancamento { get; set; }
        public Nullable<int> Parcela { get; set; }
        public Nullable<System.DateTime> Vencimento { get; set; }
        public Nullable<decimal> Valor { get; set; }
    
        public virtual FornecedoresLancamentos FornecedoresLancamentos { get; set; }
    }
}
