//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasFiscaisPedidos
    {
        public int ID { get; set; }
        public long IdNotaFiscal { get; set; }
        public Nullable<long> IdClientesPedido { get; set; }
    
        public virtual NotasFiscais NotasFiscais { get; set; }
        public virtual ClientesPedidos ClientesPedidos { get; set; }
    }
}
