//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasFiscais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotasFiscais()
        {
            this.NotasFiscaisParcelas = new HashSet<NotasFiscaisParcelas>();
            this.NotasFiscaisPedidos = new HashSet<NotasFiscaisPedidos>();
            this.NotasFiscaisProdutos = new HashSet<NotasFiscaisProdutos>();
            this.NotasFiscaisReferenciadas = new HashSet<NotasFiscaisReferenciadas>();
        }
    
        public long ID { get; set; }
        public int IdEmpresa { get; set; }
        public Nullable<long> NumeroNota { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdClienteEmail { get; set; }
        public Nullable<long> IdClienteEndereco { get; set; }
        public Nullable<int> IdFornecedor { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public Nullable<System.DateTime> DataSaida { get; set; }
        public string ConsumidorFinal { get; set; }
        public Nullable<int> ContribuinteIcms { get; set; }
        public Nullable<int> IdNaturezaOperacao { get; set; }
        public Nullable<decimal> TotalProduto { get; set; }
        public Nullable<decimal> TotalNota { get; set; }
        public Nullable<decimal> ValorServico { get; set; }
        public Nullable<decimal> Desconto { get; set; }
        public Nullable<decimal> DescontoPecas { get; set; }
        public Nullable<decimal> ValorIssqn { get; set; }
        public Nullable<decimal> PercentualIssqn { get; set; }
        public string DescricaoServico { get; set; }
        public Nullable<decimal> BaseCalculoIcms { get; set; }
        public Nullable<decimal> PercentualIcms { get; set; }
        public Nullable<decimal> TotalIcms { get; set; }
        public Nullable<decimal> TotalIpi { get; set; }
        public Nullable<decimal> BaseIcmsSubstituicao { get; set; }
        public Nullable<decimal> ValorIcmsSubstituicao { get; set; }
        public Nullable<int> IdTransportadora { get; set; }
        public Nullable<int> TipoFrete { get; set; }
        public Nullable<decimal> ValorFrete { get; set; }
        public Nullable<decimal> ValorSeguro { get; set; }
        public Nullable<decimal> OutrasDespesas { get; set; }
        public Nullable<int> QuantidadeVolumes { get; set; }
        public string EspecieVolumes { get; set; }
        public string Marca { get; set; }
        public string Numero { get; set; }
        public Nullable<decimal> PesoBruto { get; set; }
        public Nullable<decimal> PesoLiquido { get; set; }
        public string Observacao { get; set; }
        public Nullable<int> QuantidadeParcelas { get; set; }
        public Nullable<int> LocalPagamento { get; set; }
        public string Cancelada { get; set; }
        public Nullable<System.DateTime> DataCancelamento { get; set; }
        public string Motivo { get; set; }
        public string Recebedor { get; set; }
        public Nullable<decimal> TotalCusto { get; set; }
        public string IdentificadorPagamento { get; set; }
        public string TipoPagamento { get; set; }
        public string IdentificadorPresenca { get; set; }
        public string CnpjIntermediador { get; set; }
        public string NomeIntermediador { get; set; }
        public Nullable<decimal> TotalImpostoAproximado { get; set; }
        public Nullable<long> IdPedido { get; set; }
        public Nullable<long> IdOrdemServico { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdCondicaoPagamento { get; set; }
        public Nullable<int> IdFornecedorNotaEntrada { get; set; }
        public Nullable<int> IdFornecedorEndereco { get; set; }
        public Nullable<int> IdFornecedorEmail { get; set; }
        public Nullable<long> NumeroNotaFornecedor { get; set; }
        public string NumeroChaveNfe { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual ClientesEmails ClientesEmails { get; set; }
        public virtual ClientesEnderecos ClientesEnderecos { get; set; }
        public virtual CondicoesPagamentos CondicoesPagamentos { get; set; }
        public virtual Fornecedores Fornecedores { get; set; }
        public virtual NaturezaOperacoes NaturezaOperacoes { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscaisParcelas> NotasFiscaisParcelas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscaisPedidos> NotasFiscaisPedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscaisProdutos> NotasFiscaisProdutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasFiscaisReferenciadas> NotasFiscaisReferenciadas { get; set; }
        public virtual Transportadoras Transportadoras { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual ClientesServicos ClientesServicos { get; set; }
        public virtual ClientesPedidos ClientesPedidos { get; set; }
    }
}
