//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutosItens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProdutosItens()
        {
            this.ProdutosItensKits = new HashSet<ProdutosItensKits>();
            this.Atributos = new HashSet<Atributos>();
        }
    
        public long Id { get; set; }
        public long IdProduto { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> IdAtributoTipo1 { get; set; }
        public Nullable<int> IdAtributo1 { get; set; }
        public string NomeAtributo1 { get; set; }
        public string ValorAtributo1 { get; set; }
        public Nullable<int> IdAtributoTipo2 { get; set; }
        public Nullable<int> IdAtributo2 { get; set; }
        public string NomeAtributo2 { get; set; }
        public string ValorAtributo2 { get; set; }
        public Nullable<int> IdAtributoTipo3 { get; set; }
        public Nullable<int> IdAtributo3 { get; set; }
        public string NomeAtributo3 { get; set; }
        public string ValorAtributo3 { get; set; }
        public Nullable<int> IdAtributoTipo4 { get; set; }
        public Nullable<int> IdAtributo4 { get; set; }
        public string NomeAtributo4 { get; set; }
        public string ValorAtributo4 { get; set; }
        public Nullable<int> IdAtributoTipo5 { get; set; }
        public Nullable<int> IdAtributo5 { get; set; }
        public string NomeAtributo5 { get; set; }
        public string ValorAtributo5 { get; set; }
        public int QuantidadeAtual { get; set; }
        public Nullable<decimal> ValorVenda { get; set; }
        public bool Promocao { get; set; }
        public Nullable<System.DateTime> DataInicioPromocao { get; set; }
        public Nullable<System.DateTime> DataFimPromocao { get; set; }
        public Nullable<decimal> ValorPromocao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutosItensKits> ProdutosItensKits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atributos> Atributos { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
