//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taylor.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutosItensKits
    {
        public long Id { get; set; }
        public long IdProdutoPai { get; set; }
        public long IdProduto { get; set; }
        public long IdProdutoItem { get; set; }
        public int Quantidade { get; set; }
    
        public virtual ProdutosItens ProdutosItens { get; set; }
        public virtual Produtos Produtos { get; set; }
        public virtual Produtos Produtos1 { get; set; }
    }
}
